image: node:12.18

stages:
  - build-to-gcp-registry
  - deploy-to-gke-cluster
  - build-to-docker-hub

build-to-docker-hub:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  stage: build-to-docker-hub
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - docker build --no-cache --tag $CI_REGISTRY_IMAGE:$VERSION --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest

build-to-gcp-registry:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  stage: build-to-gcp-registry
  before_script:
    - base64 -d $GCP_SA_KEY | docker login -u _json_key --password-stdin https://asia.gcr.io
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - docker build --no-cache --tag asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION --tag asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .
    - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION
    - docker push asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

deploy-to-gke-cluster:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  stage: deploy-to-gke-cluster
  before_script:
    # Install CA certs, openssl to https downloads, python for gcloud sdk
    - apk add --update make ca-certificates openssl python
    - update-ca-certificates
    # Write our GCP service account private key into a file
    - base64 -d $GCP_SA_KEY > ${HOME}/gcloud-service-key.json
    # Download and install Google Cloud SDK
    - wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz
    - tar zxvf google-cloud-sdk.tar.gz && ./google-cloud-sdk/install.sh --usage-reporting=false --path-update=true
    - google-cloud-sdk/bin/gcloud --quiet components update
    - google-cloud-sdk/bin/gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
    - gcloud container clusters get-credentials memorize-cluster --zone australia-southeast1-a --project wide-strength-304907
  script:
    - kubectl set image deployment/memorize-backend memorize-backend=asia.gcr.io/$PROJECT_ID/$IMAGE_NAME:$VERSION --record
