image: node:12.18

stages:
  - build-to-docker-hub
  - build-to-gcp-registry

build-to-docker-hub:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  stage: build-to-docker-hub
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login --username $CI_REGISTRY_USER --password-stdin
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - docker build --no-cache --tag $CI_REGISTRY_IMAGE:$VERSION --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest

build-to-gcp-registry:
  services:
    - name: docker:19.03.13-dind
  image: docker:19.03.13
  stage: build-to-gcp-registry
  before_script:
    - base64 -d $GCP_SA_KEY | docker login -u _json_key --password-stdin https://gcr.io
  script:
    - export VERSION=$(cat package.json | grep version | head -1 | sed 's/[version,",:]//g' | tr -d [:space:])
    - docker build --cache-from -t asia.gcr.io/$PROJECT_ID/$IMAGE_PATH/$IMAGE_NAME:$VERSION -t asia.gcr.io/$PROJECT_ID/$IMAGE_PATH/$IMAGE_NAME:latest .
    - docker push $CI_REGISTRY_IMAGE:$VERSION
    - docker push $CI_REGISTRY_IMAGE:latest
